version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-grid
  chrome:
    image: selenium/node-chrome:4.10.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1  # Deshabilita la solicitud de contraseña en VNC
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-grid
  firefox:
    image: selenium/node-firefox:4.10.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1  # Deshabilita la solicitud de contraseña en VNC
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-grid

  app-python:
    build: .
    depends_on:
      - selenium-hub
    networks:
      - selenium-grid
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"

networks:
  selenium-grid: